# Generated by Django 4.2.20 on 2025-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile/default.png", upload_to="profile/"
            ),
        ),
    ]
