# Generated by Django 4.2.20 on 2025-05-03 12:02

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="discount_percent",
            field=models.IntegerField(
                default=0, validators=[shop.validators.validate_discount_percent]
            ),
        ),
    ]
