# Generated by Django 4.2.20 on 2025-05-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_productmodel_discount_percent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AddField(
            model_name="productmodel",
            name="brief_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
