# Generated by Django 4.2.23 on 2025-07-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_wishlistproductmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="avg_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
