# Generated by Django 4.2.20 on 2025-06-06 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0003_alter_couponmodel_used_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponmodel",
            name="used_by",
            field=models.ManyToManyField(
                blank=True, related_name="coupon_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
