# Generated by Django 4.2.20 on 2025-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_ordermodel_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.IntegerField(
                choices=[(1, "در انتظار پرداخت"), (2, "موفقیت آمیز"), (3, "لغو شده")],
                default=1,
            ),
        ),
    ]
