# Generated by Django 4.2.20 on 2025-07-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_ordermodel_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordermodel",
            options={"ordering": ["-created_date"]},
        ),
    ]
